apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: mlops-house-predictor-prod

patches:
  - target:
      kind: Namespace
      name: mlops-house-predictor
    patch: |
      - op: replace
        path: /metadata/name
        value: mlops-house-predictor-prod
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml

labels:
  - pairs:
      environment: prod
    includeSelectors: false

images:
  - name: ai-house-predictor
    newName: ai-house-predictor
    newTag: "1.0.1"
