apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: mlops-house-predictor-prod

patches:
- patch: |
    - op: replace
      path: /metadata/name
      value: mlops-house-predictor-prod
  target:
    kind: Namespace
    name: mlops-house-predictor
- path: deployment-patch.yaml
- path: configmap-patch.yaml

labels:
- pairs:
    environment: prod

images:
- name: ai-house-predictor
  newName: ghcr.io/rcazorla766/ai-house-predictor
  newTag: b364040
