apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-house-predictor-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: ai-house-predictor
    app.kubernetes.io/part-of: mlops-tfm
    environment: prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rcazorla766/Config.git
    targetRevision: main
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-house-predictor-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ApplyOutOfSyncOnly=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
