apiVersion: v1
kind: Namespace
metadata:
  name: mlops-house-predictor
  labels:
    app.kubernetes.io/name: mlops-house-predictor
    app.kubernetes.io/part-of: mlops-tfm
    app.kubernetes.io/managed-by: kustomize
